name: manim_web
description: Manim animation engine, for the web.
version: 1.0.0

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  js: ^0.6.3
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  colorize: ^3.0.0
  path: ^1.8.0
  pedantic: ^1.9.0
  progress_bar: ^1.0.0
